### ISSUE TITLE
Fresh clean checkout doesn't work - lots of missing libraries.

### ISSUE THREAD

**Issue by gabor81** [hibernate/hibernate-demos#28]
What the heck is vividsolutions? Are you sure there is no other way to declare a point? (Project.java imports)

**Comment by gabor81** [comment]
my bad, wasn't building the project properly. srry

**Comment by gunnarmorling** [comment]
Cursing and not providing any description of what actually your problem is won't get you any help. 

Consider there are humans on the other and, so adjust your tone accordingly and provide meaningful info so those willing to help can do so.

**Comment by gabor81** [comment]
I said I was sorry, and wasn't cursing. Maybe the "what the heck is vividsolutions" part, but honestly what the heck is vividsolutions? never heard of it before.

**Comment by gunnarmorling** [comment]
JTS is a library with geo-spatial data types, and this demo you apparently had trouble with is showing how to use these types with [Hibernate Spatial](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#spatial).

**Comment by gabor81** [comment]
Cool, thanks, I will take a look.

**Comment by DavideD** [comment]
THe repository for GeoDB has been deprecated, you can find an updated version of the demo here: https://github.com/DavideD/hibernate-demos/tree/update-repository
