### ISSUE TITLE
JTA transation type

### ISSUE THREAD

**Issue by tehbkaa** [hibernate/hibernate-demos#4]
Actually it's not an issue but a question. Nevertheless, it seems weird and I consider it to be an issue.
Why do you list all entity classes when using JTA transaction type? Why entity manager does not see entities by annotations? Are the any other options rather than listing all entities?

**Comment by brmeyer** [comment]
@tehbkaa, hate to sound harsh, but if it's not an issue, please don't open an issue ;)  The Hibernate mailing list, user forum, etc. are great places to start.

**Comment by tehbkaa** [comment]
I apologize for opening the ticket. I wouldn't ask if I hadn't spent a day googling and experimenting on this question. I found not many articles and examples, and this one seems to be the best. Author seem to dig and understand topic very well, so I thought he can highlight my question a bit extending his article.

Again sorry for the ticket and thanks for existing material.
