### ISSUE TITLE
Memory overflow caused by Statement ”in...“

### ISSUE THREAD

**Issue by CongminYang** [hibernate/hibernate-demos#50]
Hibernate components: How can I solve the memory overflow problem caused by Statement ”in...“?

**Comment by DavideD** [comment]
This is the repository containing the demos.

For questions about Hibernate, you can use Zulip: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user

And you need to add more details. What are the entities like? What's the query? And so on. A test case would be ideal.

Closing this issue in the meanwhile
