### ISSUE TITLE
What is Hibernate ORM's features file, obtained from a binary distro or JBoss Nexus

### ISSUE THREAD

**Issue by PashaTurok** [hibernate/hibernate-demos#7]
Could  anyone explain what is "Hibernate ORM's features file, obtained from a binary distro or JBoss Nexus". I didn't work with Nexus, I tried to enter its repo but I don't understand what is a "binary distro". If anyone could provide a link it would be great.

**Comment by gunnarmorling** [comment]
Hi, this repo contains demos around the various Hibernate projects, please use the [forum](https://forum.hibernate.org/) to ask usage questions.

The binary distro is what you get from SourceForge (http://sourceforge.net/projects/hibernate/). It's not clear to me though what you want to achieve actually? Where did you find that sentence you quoted?

I'm going to close this one, if needed please let's continue the discussion in the forum.

**Comment by PashaTurok** [comment]
This is from https://github.com/hibernate/hibernate-demos/tree/master/hibernate-orm/osgi/unmanaged-jpa instructions
